#!/bin/sh
#
# fLisp command line interpreter
#
# leg20260331, CC 1.0
#

DOUBLE="(extension 'double)"
FLISPLIB=.

{
    echo "$DOUBLE"
    echo "(bind t script_dir \"$FLISPLIB\")"
    cat core.lsp
    echo '(interp-output (open ">1")) (interp-version)';
    cat -
} |
    FLISP_INTERACTIVE=1 FLISP_QUIET=1 ./fl

